name: "Install DXC"
description: "Install DXC"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -e

        export DXC_RELEASE="v1.8.2502"
        export DXC_FILENAME="dxc_2025_02_20.zip"

        curl.exe -L --retry 5 https://github.com/microsoft/DirectXShaderCompiler/releases/download/$DXC_RELEASE/$DXC_FILENAME -o dxc.zip
        7z.exe e dxc.zip -odxc bin/x64/{dxc.exe,dxcompiler.dll}

        # We need to use cygpath to convert PWD to a windows path as we're using bash.
        cygpath --windows "$PWD/dxc" >> "$GITHUB_PATH"
