[package]
name = "voxelsim-compute"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.1"
env_logger = "0.11.8"
futures-intrusive = "0.5.0"
nalgebra = "0.33.2"
nalgebra-glm = "0.19.0"
pollster = "0.4.0"
voxelsim = { path = "../voxelsim" }
wgpu = "26.0.0"
winit = "0.30.11"
