[package]
name = "naga-fuzz"
version.workspace = true
authors.workspace = true
publish = false
edition.workspace = true
license.workspace = true
build = "build.rs"

[package.metadata]
cargo-fuzz = true

[target.'cfg(not(any(target_arch = "wasm32", target_os = "ios")))'.dependencies]
arbitrary = { workspace = true, features = ["derive"] }
libfuzzer-sys.workspace = true

[target.'cfg(not(any(target_arch = "wasm32", target_os = "ios", target_os = "visionos")))'.dependencies.naga]
workspace = true
features = ["arbitrary", "spv-in", "wgsl-in", "glsl-in"]

[build-dependencies]
cfg_aliases.workspace = true

[[bin]]
name = "spv_parser"
path = "fuzz_targets/spv_parser.rs"
bench = false
test = false
doc = false

[[bin]]
name = "wgsl_parser"
path = "fuzz_targets/wgsl_parser.rs"
bench = false
test = false
doc = false

[[bin]]
name = "glsl_parser"
path = "fuzz_targets/glsl_parser.rs"
bench = false
test = false
doc = false

[[bin]]
name = "ir"
path = "fuzz_targets/ir.rs"
bench = false
test = false
doc = false

[lints.clippy]
disallowed_types = "allow"
