[package]
name = "voxelsim-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
mavlink = "0.15.0"
nalgebra = "0.33.2"
voxelsim = { path = "../voxelsim", features = ["python"] }
pyo3={version = "0.25.1", features = ["auto-initialize"]}
