[package]
name = "hlsl-snapshots"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[lib]
name = "hlsl_snapshots"
path = "src/lib.rs"
test = false

[dependencies]
anyhow.workspace = true
nanoserde.workspace = true
